Added AI as Player 2 in AsciiGame. Created an abstract factory to create AI vs. Human CommandProcessors. Might be a bit overkill. Created a fair amount of redundancy. Consider refactoring to use a base class with overridable human vs AI templates for specific input actions (that is really the major differnce).
BUGBUG: Extermination module failed to attack the city and crashed.
==========================================
05^     15^     25^     35^     45^     55^
04^     14$i1   24$     34.     44.     54^
03^     13$     23$     33$H6   43$     53^
02^     12.     22.H5   32$i1   42$     52^
01^     11$H3   21$     31.     41.     51^
00+     10$     20$     30^     40^     50^
==========================================
[Information] AdaptaCommandProvider: Generating AI commands.
[Information] Army attacking tile at (1,1).
[Information] AttackPosition = (3,2)
[Information] EnemyPosition  = (1,1)
[Information] [Extermination] Distance to enemy: dx=2, dy=1, sum=3
[Information] AttackPosition = (3,2)
[Information] EnemyPosition  = (1,1)
[Information] [Extermination] Distance to enemy: dx=2, dy=1, sum=3
[Information] AttackPosition = (3,2)
[Information] EnemyPosition  = (1,1)
[Information] [Extermination] Distance to enemy: dx=2, dy=1, sum=3
[Information] Army at (3,2) found no valid moves this turn.
[Information] AttackPosition = (2,2)
[Information] EnemyPosition  = (1,1)
[Information] [Extermination] Distance to enemy: dx=1, dy=1, sum=2
[Information] Army moving toward (2,2) to approach target.
[Information] [Adapta] Queued 6 command(s).
[Information] AI task executing: 6: Wism.Client.Commands.Armies.SelectArmyCommand
System.InvalidOperationException: Tile already has visiting armies: Armies[5:LordBaneHero(4)]